pakfire: When there is an error copying the files...
...we will quit.

diff --git a/src/pakfire/compressor b/src/pakfire/compressor
--- a/src/pakfire/compressor
+++ b/src/pakfire/compressor
@@ -54,15 +54,21 @@ INFO=$(mktemp)
 TMP_DIR=$(mktemp -d)
 
 for rootfile in $ROOTFILES; do
-	cd / && grep -v "^#" < $rootfile | \
+	ERROR=$(cd / && \
+			grep -v "^#" < $rootfile | \
 			sed -e "s/KVER/$KVER/g" \
 				-e "s/IFS_TARGET/$IFS_TARGET/g" | \
-			cpio -pdl --quiet $TMP_DIR
+			cpio -pdl --quiet $TMP_DIR 2>&1)
+	if [ -n "${ERROR}" ]; then
+		echo -e "When copying the files, an error occoured:\n\n${ERROR}" >&2
+		rm -rf $ARCHIEVE $CONTROL $INFO $TMP_DIR
+		exit 1
+	fi
 done
 
 cd $TMP_DIR
 
-find . | cpio -o -H newc --quiet | lzma -czv - > $ARCHIEVE
+find . | cpio -o -H newc --quiet | lzma -cz - > $ARCHIEVE
 
 cat <<EOF >$INFO
 ### $NAME package
