naoki: Mixed things.
(Can't break this down to several commits.)

 - Changed layout of the package files (slightly).

diff --git a/pkgs/Rules b/pkgs/Rules
--- a/pkgs/Rules
+++ b/pkgs/Rules
@@ -3,117 +3,43 @@
 include $(dir $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST)))/gmsl
 
 STAGE_PACKAGE_TARGETS = $(call reverse,$(PKG_PACKAGES))
-
-STAGE_PREPARE = $(ROOT)/.prepared
-STAGE_BUILD   = $(ROOT)/.built
-STAGE_INSTALL = $(ROOT)/.installed
-STAGE_PACKAGE = $(STAGE_PACKAGE_TARGETS)
-
-define PRE_PREPARE
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Preparation started"
-	echo "#####################################################################"
-endef
-
-define POST_PREPARE
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Preparation finished"
-	echo "#####################################################################"
-	touch $(STAGE_PREPARE)
-endef
-
-define PRE_BUILD
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Build started"
-	echo "#####################################################################"
-endef
-
-define POST_BUILD
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Build finished"
-	echo "#####################################################################"
-	touch $(STAGE_BUILD)
-endef
-
-define PRE_INSTALL
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Install started"
-	echo "#####################################################################"
-endef
-
-define POST_INSTALL
-	echo "#####################################################################"
-	echo "# $(PKG_NAME) - Install finished"
-	echo "#####################################################################"
-
-	$(DO_QUALITY_AGENT)
-
-	# Dump filelist
-	cd $(BUILDROOT) && find -ls
-
-	touch $(STAGE_INSTALL)
-endef
-
-.PHONY: prepare build install package
-prepare: $(STAGE_PREPARE)
-build  : $(STAGE_BUILD)
-install: $(STAGE_INSTALL)
-package: $(STAGE_PACKAGE)
-
-download: $(OBJECTS)
+STAGE_DONE = $(ROOT)/.done
 
 info:
 	@echo "PKG_BUILD_DEPENDENCIES=\"$(PKG_BUILD_DEPS)\""
 	@echo "PKG_DEPENDENCIES=\"$(PKG_DEPS)\""
-	@echo "PKG_DESCRIPTION=\"$(value PKG_DESCRIPTION)\""
-	@echo "PKG_FILES=\"$(objects)\""
+	@echo "PKG_DESCRIPTION=\"$(strip $(PKG_DESCRIPTION))\""
 	@echo "PKG_GROUP=\"$(PKG_GROUP)\""
 	@echo "PKG_LICENSE=\"$(PKG_LICENSE)\""
 	@echo "PKG_MAINTAINER=\"$(PKG_MAINTAINER)\""
 	@echo "PKG_NAME=\"$(PKG_NAME_REAL)\""
+	@echo "PKG_OBJECTS=\"$(strip $(PKG_OBJECTS))\""
 	@echo "PKG_PACKAGES=\"$(PKG_PACKAGES)\""
 	@echo "PKG_PACKAGES_FILES=\"$(PKG_PACKAGES_FILES)\""
 	@echo "PKG_VER=\"$(PKG_VER)\""
 	@echo "PKG_REL=\"$(PKG_REL)\""
-	@echo "PKG_SUMMARY=\"$(PKG_SUMMARY)\""
+	@echo "PKG_SUMMARY=\"$(strip $(PKG_SUMMARY))\""
 	@echo "PKG_URL=\"$(PKG_URL)\""
 ifeq "$(TOOLCHAIN)" "1"
 	@echo "PKG_TOOLCHAIN_DEPS=\"$(PKG_TOOLCHAIN_DEPS)\""
 endif
 
 $(OBJECTS):
-	$(DO_LOAD)
+	@echo "Object file \"$@\" is required." >&2
+	@exit 1
 
-$(STAGE_PACKAGE_TARGETS): $(STAGE_INSTALL)
+$(STAGE_PACKAGE_TARGETS): $(STAGE_DONE)
 	@echo "$(strip $(PKG_FILES_$@))" > $(DIR_TMP)/filelist_$@
 	@/usr/src/src/pakfire/compressor $(DIR_PACKAGES)/$(call DO_PACKAGE_FILENAME,$@) \
 		--root=$(BUILDROOT) $(if $(PKG_FILES_$@), --regexes=$(DIR_TMP)/filelist_$@)
 
-$(STAGE_PREPARE): $(OBJECTS)
-	@$(PRE_PREPARE)
-ifneq "$(PKG_TARBALL)" ""
-	cd $(DIR_SRC) && $(DO_EXTRACT) $(DIR_DL)/$(PKG_TARBALL)
-endif
+package: $(STAGE_PACKAGE_TARGETS)
 
-	$(DO_PATCHES)
+shell: $(OBJECTS)
+	$(if $(STAGE_PREPARE),$(DO_PREPARE))
 
-	@$(POST_PREPARE)
-
-$(STAGE_BUILD): $(STAGE_PREPARE)
-	$(PRE_BUILD)
-
-	cd $(DIR_APP) && \
-		./configure \
-			$(CONFIGURE_ARCH) \
-			--prefix=/usr
-
-	cd $(DIR_APP) && make $(PARALLELISMFLAGS)
-
-	$(POST_BUILD)
-
-$(STAGE_INSTALL): $(STAGE_BUILD)
-	@$(PRE_INSTALL)
-
-	cd $(DIR_APP) && make install $(if $(TOOLCHAIN),,DESTDIR=$(BUILDROOT))
-
-	@$(POST_INSTALL)
+$(STAGE_DONE): $(OBJECTS)
+	$(if $(STAGE_PREPARE),$(DO_PREPARE))
+	$(if $(STAGE_BUILD),$(DO_BUILD))
+	$(if $(STAGE_INSTALL),$(DO_INSTALL))
+	@touch $@
diff --git a/tools/naoki-functions b/tools/naoki-functions
--- a/tools/naoki-functions
+++ b/tools/naoki-functions
@@ -19,8 +19,8 @@ function exithandler() {
 		done <<<"${mounts}"
 	done
 
-	if [ "${ERROR}" != "1" ]; then
-		[ -d "${BUILD_DIR}" ] && rm -rf ${BUILD_DIR}
+	if [ ! -e "${BUILD_DIR}/.failed" ]; then
+		rm -rf ${BUILD_DIR}
 	fi
 
 	log DEBUG "Shut down naoki instance with pid $$."
@@ -60,13 +60,11 @@ function naoki_prepare() {
 	local p=$(find_package ${1})
 	shift
 
-
-
 	msg "Preparing environment ${BUILD_DIR}..."
 
 	mkdir -p \
 		${BUILD_DIR} \
-		${BUILD_DIR}/{root,tmp} \
+		${BUILD_DIR}/{boot,root,tmp} \
 		${BUILD_DIR}/{dev,proc,sys} \
 		${BUILD_DIR}/{,usr/}{bin,lib,sbin} \
 		${BUILD_DIR}/usr/src \
@@ -85,18 +83,38 @@ function naoki_prepare() {
 		mount --bind /${i} ${BUILD_DIR}/${i}
 	done
 
-	CHROOT=0 naoki_make ${p} --without-chroot download
+	local object
+	local to_download
+	for object in $(package_objects ${p}); do
+		if [ -e "${DIR_TARBALLS}/${object}" ] || \
+			[ -e "${DIR_PATCHES}/${object}" ]; then
+			continue
+		fi
+		to_download="${to_download} ${object}"
+	done
+	if [ -n "${to_download}" ]; then
+		log DEBUG "Going to get file(s): ${to_download}"
+		${DOWNLOADER} --tarballs="${DIR_TARBALLS}" \
+			--patches="${DIR_PATCHES}" ${to_download}
+		if [ "$?" != "0" ]; then
+			return 1
+		fi
+	fi
 
 	# Extract needed packages
-	local pkg_dependencies=$(dependencies_resolve ${p} | tr "\n" " ")
+	local pkg_dependencies=$(package_dependencies_for_build ${p})
 	msg "  Resolving dependencies: ${pkg_dependencies-None}"
 	local dep
+	local missing
 	for dep in ${pkg_dependencies}; do
 		if ! package_is_built ${dep}; then
-			msg "Dependencies for ${p} are missing. Cannot prepare."
-			return 4
+			missing="${missing} ${dep}"
 		fi
 	done
+	if [ -n "${missing}" ]; then
+		msg "Dependencies for ${p} are missing: ${missing}"
+		return 4
+	fi
 
 	for dep in ${pkg_dependencies}; do
 		msg "Decompressing ${dep}..."
@@ -111,8 +129,7 @@ function naoki_prepare() {
 		ln -sf ${TOOLS_DIR}${i} ${BUILD_DIR}${i}
 	done
 
-	naoki_make ${p} prepare $@
-	return $?
+	return 0
 }
 
 function naoki_cleanup() {
@@ -219,18 +236,8 @@ function naoki_make() {
 	fi
 	cmd="${cmd} -f ${p##*/}.nm"
 
-	naoki_cmd ${p} "${cmd}" $@ 2>&1 | __erase_log
+	naoki_cmd ${p} "${cmd}" $@
 	return ${PIPESTATUS[0]}
-}
-
-function __erase_log() {
-	local line
-
-	local IFS='\n'
-	while read line; do
-		grep -q "commands for target" <<<"${line}" && continue
-		echo -e "${line}"
-	done
 }
 
 function naoki_build() {
@@ -248,27 +255,12 @@ function naoki_build() {
 		exit ${ret}
 	fi
 
-	naoki_make ${p} build $@
-	ret=$?
-
-	if [  "${ret}" != "0" ]; then
-		error "Build command failed."
-		exit ${ret}
-	fi
-	
-	naoki_make ${p} install $@
-	ret=$?
-
-	if [  "${ret}" != "0" ]; then
-		error "Install command failed."
-		exit ${ret}
-	fi
-
 	naoki_make ${p} package $@
 	ret=$?
 
 	if [  "${ret}" != "0" ]; then
-		error "Package command failed."
+		error "Package build failed."
+		touch ${BUILD_DIR}/.failed
 		exit ${ret}
 	fi
 }
@@ -290,6 +282,7 @@ function naoki_shell() {
 	shift
 
 	naoki_prepare ${p}
+	naoki_make ${p} shell
 
 	# A little help message
 	echo
@@ -306,7 +299,7 @@ function naoki_shell() {
 
 	naoki_cmd ${p} "bash --login"
 	local ret=$?
-	
+
 	echo
 	echo    "Exit code: ${ret}"
 	echo
