Wrote nice initscripts for the installer.
git-svn-id: http://svn.ipfire.org/svn/ipfire/trunk@1106 ea5c0bd1-69bd-2848-81d8-4f18e57aeed8

diff --git a/src/initscripts/init.d/functions b/src/initscripts/init.d/functions
--- a/src/initscripts/init.d/functions
+++ b/src/initscripts/init.d/functions
@@ -22,7 +22,7 @@ export PATH="/bin:/usr/bin:/sbin:/usr/sbin"
 RELOADSIG="HUP"
 
 # Number of seconds between STOPSIG and FALLBACK when stopping processes
-KILLDELAY="10"
+KILLDELAY="3"
 
 ## Screen Dimensions
 # Find current screen size
@@ -40,12 +40,23 @@ fi
 COL=$((${COLUMNS} - 8))
 WCOL=$((${COL} - 2))
 
-## Set Cursor Position Commands, used via echo -e
+## Provide an echo that supports -e and -n
+# If formatting is needed, $ECHO should be used
+case "`echo -e -n test`" in
+	-[en]*)
+		ECHO=/bin/echo
+		;;
+	*)
+		ECHO=echo
+		;;
+esac
+
+## Set Cursor Position Commands, used via $ECHO
 SET_COL="\\033[${COL}G"      # at the $COL char
 SET_WCOL="\\033[${WCOL}G"    # at the $WCOL char
 CURS_UP="\\033[1A\\033[0G"   # Up one line, at the 0'th char
 
-## Set color commands, used via echo -e
+## Set color commands, used via $ECHO
 # Please consult `man console_codes for more information
 # under the "ECMA-48 Set Graphics Rendition" section
 #
@@ -99,12 +110,11 @@ boot_mesg()
 	done
 
 	## Figure out the length of what is to be printed to be used
-        ## for warning messges. 
-	STRING_LENGTH="`echo "${1}" | sed \
-		-e 's,.,.,g' -e 'l 1' | grep -c \$`"
+	## for warning messages. 
+	STRING_LENGTH=$((${#1} + 1))
 
 	# Print the message to the screen
-	echo ${ECHOPARM} -e "${2}${1}"
+	${ECHO} ${ECHOPARM} -e "${2}${1}"
 	
 }
 
@@ -117,27 +127,27 @@ boot_mesg_flush()
 boot_log()
 {
 	# Left in for backwards compatibility
-	echo -n ""
+	:
 }
 
 echo_ok()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${SUCCESS}  OK  ${BRACKET}]"
-	echo -e "${NORMAL}"
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${SUCCESS}  OK  ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
         boot_mesg_flush
 }
 
 echo_failure()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${FAILURE} FAIL ${BRACKET}]"
-	echo -e "${NORMAL}"
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${FAILURE} FAIL ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
         boot_mesg_flush
 }
 
 echo_warning()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${WARNING} WARN ${BRACKET}]"
-	echo -e "${NORMAL}"
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${WARNING} WARN ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
         boot_mesg_flush
 }
 
@@ -152,12 +162,12 @@ print_error_msg()
 	boot_mesg_flush
 	boot_mesg -n "If you're able to track this"
 	boot_mesg -n " error down to a bug in one of the files provided by"
-	boot_mesg -n " ipfire, please be so kind to inform us at"
-	boot_mesg " info@ipfire.org.\n"
+	boot_mesg -n " the LFS book, please be so kind to inform us at"
+	boot_mesg " lfs-dev@linuxfromscratch.org.\n"
 	boot_mesg_flush
-	boot_mesg -n "Press Enter to continue or wait 3 minutes..." ${INFO}
+	boot_mesg -n "Press Enter to continue..." ${INFO}
 	boot_mesg "" ${NORMAL}
-	read -t 180 ENTER
+	read ENTER
 }
 
 check_script_status()
@@ -209,20 +219,20 @@ print_status()
 			# may call it this way.
 			case "${2}" in
 				running)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Already running." ${WARNING}
 					echo_warning
 					;;
 				not_running)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Not running." ${WARNING}
 					echo_warning
 					;;
 				not_available)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Not available." ${WARNING}
 					echo_warning
 					;;
@@ -244,15 +254,44 @@ print_status()
 
 reloadproc()
 {
-	if [ "${#}" = "0" ]; then
-		echo "Usage: reloadproc [{program}]"
-		exit 1
+	local pidfile=""
+	local failure=0
+
+	while true
+	do
+		case "${1}" in
+			-p)
+				pidfile="${2}"
+				shift 2
+				;;
+			-*)
+				log_failure_msg "Unknown Option: ${1}"
+				return 2
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+
+	if [ "${#}" -lt "1" ]; then
+		log_failure_msg "Usage: reloadproc [-p pidfile] pathname"
+		return 2
 	fi
 
-	getpids "${1}"
+	# This will ensure compatibility with previous LFS Bootscripts
+	if [ -n "${PIDFILE}" ];	then
+		pidfile="${PIDFILE}"
+	fi
+
+	# Is the process running?
+	if [ -z "${pidfile}" ];	then
+		pidofproc -s "${1}"
+	else
+		pidofproc -s -p "${pidfile}" "${1}"
+	fi
 
 	if [ -n "${pidlist}" ];	then
-		failure="0"
 		for pid in ${pidlist}
 		do
 			kill -"${RELOADSIG}" "${pid}" || failure="1"
@@ -269,30 +308,70 @@ reloadproc()
 
 statusproc()
 {
-	if [ "${#}" = "0" ]
-	then
-		echo "Usage: statusproc {program}"
-		exit 1
+	local pidfile=""
+	local base=""
+	local ret=""
+
+	while true
+	do
+		case "${1}" in
+			-p)
+				pidfile="${2}"
+				shift 2
+				;;
+			-*)
+				log_failure_msg "Unknown Option: ${1}"
+				return 2
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+
+	if [ "${#}" != "1" ]; then
+		shift 1
+		log_failure_msg "Usage: statusproc [-p pidfile] pathname"
+		return 2
 	fi
 
-	getpids "${1}"
+	# Get the process basename
+	base="${1##*/}"
+
+	# This will ensure compatibility with previous LFS Bootscripts
+	if [ -n "${PIDFILE}" ];	then
+		pidfile="${PIDFILE}"
+	fi
+
+	# Is the process running?
+	if [ -z "${pidfile}" ];	then
+		pidofproc -s "${1}"
+	else
+		pidofproc -s -p "${pidfile}" "${1}"
+	fi
+
+	# Store the return status
+	ret=$?
 
 	if [ -n "${pidlist}" ];	then
-		echo -e "${INFO}${base} is running with Process"\
+		${ECHO} -e "${INFO}${base} is running with Process"\
 			"ID(s) ${pidlist}.${NORMAL}"
 	else
 		if [ -n "${base}" -a -e "/var/run/${base}.pid" ]; then
-			echo -e "${WARNING}${1} is not running but"\
+			${ECHO} -e "${WARNING}${1} is not running but"\
 				"/var/run/${base}.pid exists.${NORMAL}"
 		else
-			if [ -n "${PIDFILE}" -a -e "${PIDFILE}" ]; then
-				echo -e "${WARNING}${1} is not running"\
-					"but ${PIDFILE} exists.${NORMAL}"
+			if [ -n "${pidfile}" -a -e "${pidfile}" ]; then
+				${ECHO} -e "${WARNING}${1} is not running"\
+					"but ${pidfile} exists.${NORMAL}"
 			else
-				echo -e "${INFO}${1} is not running.${NORMAL}"
+				${ECHO} -e "${INFO}${1} is not running.${NORMAL}"
 			fi
 		fi
 	fi
+
+	# Return the status from pidofproc
+	return $ret
 }
 
 # The below functions are documented in the LSB-generic 2.1.0
@@ -363,11 +442,11 @@ pidofproc()
 		for pid in ${lpids}
 		do
 			if [ "${pid}" -ne "$$" -a "${pid}" -ne "${PPID}" ]; then
-				kill -0 "${pid}" > /dev/null &&
+				kill -0 "${pid}" 2>/dev/null &&
 				pidlist="${pidlist} ${pid}"
 			fi
 			
-			if [ "${silent}" -ne "1" ]; then
+			if [ "${silent}" != "1" ]; then
 				echo "${pidlist}"
 			fi
 
@@ -380,7 +459,7 @@ pidofproc()
 
 	else
 		pidlist=`pidof -o $$ -o $PPID -x "$1"`
-		if [ "x${silent}" != "x1" ]; then
+		if [ "${silent}" != "1" ]; then
 			echo "${pidlist}"
 		fi
 
@@ -529,10 +608,10 @@ loadproc()
 killproc()
 {
 	local pidfile=""
-	local killsig=""
+	local killsig=TERM # default signal is SIGTERM
 	pidlist=""
 
-# This will ensure compatibility with previous LFS Bootscripts
+	# This will ensure compatibility with previous LFS Bootscripts
 	if [ -n "${PIDFILE}" ];	then
 		pidfile="${PIDFILE}"
 	fi
@@ -547,7 +626,7 @@ killproc()
 			-*)
 				log_failure_msg "Unknown Option: ${1}"
 				return 2
-			;;
+				;;
 			*)
  				break
 				;;
@@ -562,37 +641,49 @@ killproc()
 		return 2
 	fi
 
+	# Is the process running?
 	if [ -z "${pidfile}" ];	then
 		pidofproc -s "${1}"
 	else
 		pidofproc -s -p "${pidfile}" "${1}"
 	fi
 
-    # Change....
+    # If running, send the signal
     if [ -n "${pidlist}" ]; then
 	for pid in ${pidlist}
 	do
-		kill -${killsig:-TERM} ${pid} 2>/dev/null
-		if [ -z "${killsig}" ]; then
-			# Wait up to 3 seconds, for ${pid} to terminate
-			local dtime=${KILLDELAY}
+		kill -${killsig} ${pid} 2>/dev/null
+
+		# Wait up to 3 seconds, for ${pid} to terminate
+		case "${killsig}" in
+		TERM|SIGTERM|KILL|SIGKILL)
+			# sleep in 1/10ths of seconds and
+			# multiply KILLDELAY by 10
+			local dtime="${KILLDELAY}0"
 			while [ "${dtime}" != "0" ]
 			do
 				kill -0 ${pid} 2>/dev/null || break
-				sleep 1
+				sleep 0.1
 				dtime=$(( ${dtime} - 1))
 			done
 			# If ${pid} is still running, kill it
 			kill -0 ${pid} 2>/dev/null && kill -KILL ${pid} 2>/dev/null
-		fi
+			;;
+		esac
 	done
 
-	if [ -z "${killsig}" ];	then
-		pidofproc -s "${1}"
+	# Check if the process is still running if we tried to stop it
+	case "${killsig}" in
+	TERM|SIGTERM|KILL|SIGKILL)
+		if [ -z "${pidfile}" ];	then
+			pidofproc -s "${1}"
+		else
+			pidofproc -s -p "${pidfile}" "${1}"
+		fi
 
 		# Program was terminated
 		if [ "$?" != "0" ]; then
-			# Pidfile Exists
+			# Remove the pidfile if necessary
 			if [ -f "${pidfile}" ];	then
 				rm -f "${pidfile}"
 			fi
@@ -602,17 +693,13 @@ killproc()
 			echo_failure
 			return 4 # Unknown Status
 		fi
-	else
-		if [ -z "${pidfile}" ];	then
-			pidofproc -s "${1}"
-		else
-			pidofproc -s -p "${pidfile}" "${1}"
-		fi
-	fi
-
-	evaluate_retval # This is "Probably" not LSB compliant, but required to be compatible with older bootscripts
-
-    else
+		;;
+	*)
+		# Just see if the kill returned successfully
+		evaluate_retval
+		;;
+	esac
+    else # process not running
 	print_status warning not_running
     fi
 }
@@ -634,8 +721,8 @@ killproc()
 #*******************************************************************************
 log_success_msg()
 {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${SUCCESS}""  OK  ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${SUCCESS}""  OK  ""${BRACKET}""]""${NORMAL}"
 	return 0
 }
 
@@ -654,8 +741,8 @@ log_success_msg()
 #
 #*******************************************************************************
 log_failure_msg() {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${FAILURE}"" FAIL ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${FAILURE}"" FAIL ""${BRACKET}""]""${NORMAL}"
 	return 0
 }
 
@@ -674,26 +761,9 @@ log_failure_msg() {
 #
 #*******************************************************************************
 log_warning_msg() {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${WARNING}"" WARN ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${WARNING}"" WARN ""${BRACKET}""]""${NORMAL}"
 	return 0
-}
-
-run_subdir() {
-	DIR=$1
-	for i in $(ls -v ${DIR}* 2> /dev/null); do
-		check_script_status
-		OUT=$(echo $(basename ${i}) | awk -F- '{ print $2 }')
-		case "$OUT" in
-			S) ${i} start	;;
-			K) ${i} stop ;;
-			RS) ${i} restart ;;
-			RL) ${i} reload	;;
-			U) ${i} up ;;
-			D) ${i} down ;;
-			*) ${i} ;;
-		esac
-	done
 }
 
 # End $rc_base/init.d/functions
