Worked again on that networking stuff.

diff --git a/src/initscripts/networking/functions b/src/initscripts/networking/functions
--- a/src/initscripts/networking/functions
+++ b/src/initscripts/networking/functions
@@ -30,17 +30,26 @@ function is_mac() {
 
 function get_device_by_mac() {
 	local mac
-	local i
+	local device
 
 	mac=$1
 
-	for i in /sys/class/net/*; do
-		if [ "$(cat $i/address)" = "$mac" ]; then
-			grep -q "^${i##*/}" /proc/net/vlan/config 2>/dev/null && continue
-			echo ${i##*/}
-			break
+	for device in /sys/class/net/*; do
+		if [ "$(cat $device/address)" = "$mac" ]; then
+			device=${device##*/}
+			# Skip virtual devices
+			if [ -e "/proc/net/vlan/$device" ]; then
+				continue
+			fi
+			# Skip zones
+			if zone_exists ${device}; then
+				continue
+			fi
+			echo ${device}
+			return 0
 		fi
 	done
+	return 1
 }
 
 function get_device_by_mac_and_vid() {
@@ -53,13 +62,15 @@ function get_device_by_mac_and_vid() {
 	local i
 	local VID
 	local DEVICE
-	grep '|' < /proc/net/vlan/config 2>/dev/null | sed "s/|//g" | \
-		while read DEVICE VID PARENT; do
-			if [ "${vid}" = "${VID}" ] && [ "$(macify ${PARENT})" = "${mac}" ]; then
-				echo "${DEVICE}"
-				return 0
-			fi
-		done
+	if [ -e "/proc/net/vlan/config" ]; then
+		grep '|' /proc/net/vlan/config | sed "s/|//g" | \
+			while read DEVICE VID PARENT; do
+				if [ "${vid}" = "${VID}" ] && [ "$(macify ${PARENT})" = "${mac}" ]; then
+					echo "${DEVICE}"
+					return 0
+				fi
+			done
+	fi
 	return 1
 }
 
@@ -95,7 +106,13 @@ function devicify() {
 		mac=${device}
 		device=$(get_device_by_mac ${device})
 	fi
-	echo ${device}
+	if [ -n "${device}" ]; then
+		echo ${device}
+		return 0
+	else
+		echo "devicify: Could not find device of $@" >&2
+		return 1
+	fi
 }
 
 function macify() {
@@ -123,12 +140,28 @@ function rename_device() {
 	source=$1
 	destination=$2
 
+	# Replace + by a valid number
+	if grep -q "+$" <<<${destination}; then
+		local number
+		destination=$(sed -e "s/+//" <<<$destination)
+		number=0
+		while :; do
+			if ! device_exists "${destination}${number}"; then
+				destination="${destination}${number}"
+				break
+			fi
+			number=$(($number + 1))
+		done
+	fi
+
 	# Check if devices exist
 	if ! device_exists ${source} || device_exists ${destination}; then
 		return 4
 	fi
 
+	ip link set ${source} down
 	ip link set ${source} name ${destination}
+	ip link set ${destination} up
 	return $?
 }
 
diff --git a/src/initscripts/networking/port b/src/initscripts/networking/port
--- a/src/initscripts/networking/port
+++ b/src/initscripts/networking/port
@@ -27,77 +27,65 @@ action=$2
 
 shift 2
 
+if [ -z "${port}" ] || [ -z "${action}" ]; then
+	echo "Usage: $0 <port> <up|down|attach|detach> [hooks]"
+	echo
+	exit 1
+fi
+
 if ! device_exists ${port}; then
 	echo "Port ${port} does not exist."
 	exit 1
 fi
 
-if [ -z "${port}" ] || [ -z "${action}" ]; then
-	echo "Usage: $0 <port> <up|down> [hooks]"
-	echo
-fi
-
 for arg in ${@-$(find ${CONFIG_PORTS}/${port}/)}; do
+	[ -L "${arg}" ] && arg=$(readlink ${arg})
 	arg=${arg##*/}
 	[ -e "${CONFIG_PORTS}/${port}/${arg}" ] || continue
 	hooks="${hooks} ${CONFIG_PORTS}/${port}/${arg}"
 done
-
-# Getting zone variable
-#local zone
-#if [ -z "$ZONE" ]; then
-#	for zone in $(all_zones); do
-#		for i in ${zone}/port-*; do
-#			i=$(readlink ${i})
-#			for j in ${ports}; do
-#				if [ "${i}" = "${j}" ]; then
-#					ZONE=${i%/*}
-#					ZONE=${ZONE##*/}
-#				fi
-#			done
-#		done
-#	done
-#fi
 
 case "$action" in
 	up)
 		message="Setting up port ${port}..."
 		ip link set $(devicify ${port}) up
 		evaluate_retval
-
-		for hook in ${hooks}; do
-			[ -d "${hook}" ] && continue
-			(
-				. ${hook}
-				if [ -n "${HOOK}" -a -x "/etc/init.d/networking/hooks/${HOOK}" ]; then
-					CONFIG=${hook} /etc/init.d/networking/hooks/${HOOK} ${port} up
-				else
-					echo -e "${FAILURE}Unable to process ${hook}. Either"
-					echo -e "${FAILURE}the HOOK variable was not set,"
-					echo -e "${FAILURE}or the specified hook cannot be executed."
-					message=""
-					log_failure_msg
-				fi
-			)
-		done
 		;;
-	down)
-		for hook in ${hooks}; do
-			[ -d "${hook}" ] && continue
-			(
-				. ${hook}
-				if [ -n "${HOOK}" -a -x "/etc/init.d/networking/hooks/${HOOK}" ]; then
-					CONFIG=${hook} /etc/init.d/networking/hooks/${HOOK} ${port} down
-				else
-					echo -e "${FAILURE}Unable to process ${hook}. Either"
-					echo -e "${FAILURE}the HOOK variable was not set,"
-					echo -e "${FAILURE}or the specified hook cannot be executed."
-					message=""
-					log_failure_msg
-				fi
-			)
-		done
 
+	down)
+		;;
+
+	attach|detach)
+		if [ -z "${ZONE}" ]; then
+			log_failure_msg "ZONE is not set."
+			exit 1
+		fi
+		;;
+
+	*)
+		log_failure_msg "\"${action}\" is not a valid command."
+		exit 1
+		;;
+esac
+
+for hook in ${hooks}; do
+	[ -d "${hook}" ] && continue
+	(
+		. ${hook}
+		if [ -n "${HOOK}" -a -x "/etc/init.d/networking/hooks/${HOOK}" ]; then
+			CONFIG=${hook} /etc/init.d/networking/hooks/${HOOK} ${port} ${action}
+		else
+			echo -e "${FAILURE}Unable to process ${hook}. Either"
+			echo -e "${FAILURE}the HOOK variable was not set,"
+			echo -e "${FAILURE}or the specified hook cannot be executed."
+			message=""
+			log_failure_msg
+		fi
+	)
+done
+
+case "${action}" in
+	down)
 		message="Pushing down port ${port}..."
 		ip link set $(devicify ${port}) down
 		evaluate_retval
