naoki: Throw a warning when package is tried to be decompressed but was not built, yet.

diff --git a/tools/common-package-functions b/tools/common-package-functions
--- a/tools/common-package-functions
+++ b/tools/common-package-functions
@@ -411,6 +411,10 @@ function package_decompress() {
 	local file
 	local pkg
 	for pkg in $@; do
+		if ! package_is_built ${pkg}; then
+			log WARNING "Cannot extract package \"${pkg}\". It has not been built, yet."
+			continue
+		fi
 		for file in $(package_packages ${pkg}); do
 			PATH=${TOOLS_DIR}/sbin:${TOOLS_DIR}/bin:${PATH} \
 				${BASEDIR}/src/pakfire/decompressor --root=${BUILD_DIR} \
