Worked on buildscripts, again.
We now send the stage and built package to buildspy.
We also set a marker, when a build failed and don't
repeat the mistake. If git pull can get updates, we
reset and repeat building.

diff --git a/tools/make-batch b/tools/make-batch
--- a/tools/make-batch
+++ b/tools/make-batch
@@ -33,7 +33,14 @@ batch_start() {
 
 	[ "$1" = "--clean" ] && $0 clean
 
-	yes "y" | git_pull --batch
+	git_pull --batch
+
+	if [ -e "$FAILED" ]; then
+		echo -n "Last build failed..."
+		beautify message FAIL
+		exit 1
+	fi
+
 	screen -dmS ipfire $0 batch _run
 }
 
