Worked on buildscripts, again.
./make.sh ---
            |`- toolchain [get|put]
             `- source    [get|put]

diff --git a/tools/make-include b/tools/make-include
--- a/tools/make-include
+++ b/tools/make-include
@@ -126,7 +126,6 @@ mkdir $BASEDIR/log_${MACHINE}/ 2>/dev/null
 
 # Set up what used to be /tools
 TOOLS_DIR=/tools_${MACHINE}
-CTOOLS_DIR=/cross-tools_${MACHINE}
 
 # Set up /installer
 INSTALLER_DIR=/installer
@@ -146,6 +145,9 @@ UCLIBC_CC_CORE_STATIC_DIR=${UCLIBC_DIR}/gcc-core-static
 
 #UCLIBC_SYSROOT_DIR=${UCLIBC_DIR}/${UCLIBC_TARGET}/sys-root
 UCLIBC_SYSROOT_DIR=${INSTALLER_DIR}
+
+# A file that indicates that we are running
+RUNNING=$BASEDIR/.running
 
 ###############################################################################
 #
@@ -181,14 +183,49 @@ SET_TIME_COL="\\033[${TIME_COL}G"
 SET_VER_COL="\\033[${VER_COL}G"
 SET_OPT_COL="\\033[${OPT_COL}G"
 
-# Define color for messages
-BOLD="\\033[1;39m"
-DONE="\\033[1;32m"
-SKIP="\\033[1;34m"
-WARN="\\033[1;35m"
-FAIL="\\033[1;31m"
-NORMAL="\\033[0;39m"
+# Normal colors
+CLR_NORM_BLK="\\033[0;30m"    # black
+CLR_NORM_RED="\\033[0;31m"    # red
+CLR_NORM_GRN="\\033[0;32m"    # green
+CLR_NORM_YEL="\\033[0;33m"    # yellow
+CLR_NORM_BLU="\\033[0;34m"    # blue
+CLR_NORM_MAG="\\033[0;35m"    # magenta
+CLR_NORM_CYN="\\033[0;36m"    # cyan
+CLR_NORM_WHT="\\033[0;37m"    # white
+CLR_NORM_GRY="\\033[0;39m"    # grey
 
+# Emphased colors
+CLR_BOLD_BLK="\\033[1;30m"    # black
+CLR_BOLD_RED="\\033[1;31m"    # red
+CLR_BOLD_GRN="\\033[1;32m"    # green
+CLR_BOLD_YEL="\\033[1;33m"    # yellow
+CLR_BOLD_BLU="\\033[1;34m"    # blue
+CLR_BOLD_MAG="\\033[1;35m"    # magenta
+CLR_BOLD_CYN="\\033[1;36m"    # cyan
+CLR_BOLD_WHT="\\033[1;37m"    # white
+CLR_BOLD_GRY="\\033[1;39m"    # grey
+
+# Background colors
+CLR_BACK_BLK="\\033[40m"      # black
+CLR_BACK_RED="\\033[41m"      # red
+CLR_BACK_GRN="\\033[42m"      # green
+CLR_BACK_YEL="\\033[43m"      # yellow
+CLR_BACK_BLU="\\033[44m"      # blue
+CLR_BACK_MAG="\\033[45m"      # magenta
+CLR_BACK_CYN="\\033[46m"      # cyan
+CLR_BACK_WHT="\\033[47m"      # white
+
+# Action colors
+BOLD=$CLR_BOLD_GRY
+DONE=$CLR_BOLD_GRN
+SKIP=$CLR_BOLD_BLU
+WARN=$CLR_BOLD_MAG
+FAIL=$CLR_BOLD_RED
+NORMAL=$CLR_NORM_GRY
+
+# Color hooks
+BRACKET_L="${CLR_BOLD_BLU}[${NORMAL}"
+BRACKET_R="${CLR_BOLD_BLU}]${NORMAL}"
 
 ################################################################################
 #                                                                              #
@@ -203,17 +240,13 @@ NORMAL="\\033[0;39m"
 . $BASEDIR/tools/make-git
 
 evaluate() {
-	if [ "$?" -eq "0" ]; then
+	RETVAL=$?
+	if [ "$RETVAL" -eq "0" ]; then
 		beautify message DONE
 	else
-		EXITCODE=$1
-		shift 1
 		beautify message FAIL
-		$*
-		if [ $EXITCODE -ne "0" ]; then
-			exit $EXITCODE
-		fi
 	fi
+	(exit $RETVAL)
 }
 
 position_cursor()
@@ -253,26 +286,16 @@ beautify()
 	case "$1" in
 		message)
 			MESSAGE="$3"
+			echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}${BRACKET_L}"
 			case "$2" in
-				DONE)
-					echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${DONE} DONE ${NORMAL}]\n"
-					;;
-				WARN)
-					echo -ne "${WARN}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${WARN} WARN ${NORMAL}]\n"
-					;;	
-				FAIL)
-					echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${FAIL} FAIL ${NORMAL}]\n"
-					;;
-				SKIP)
-					echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${SKIP} SKIP ${NORMAL}]\n"
-					;;
-				ON)
-					echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${DONE}  ON  ${NORMAL}]\n"
-					;;
-				OFF)
-					echo -ne "${BOLD}${MESSAGE}${NORMAL}${SET_RESULT_COL}[${FAIL} OFF  ${NORMAL}]\n"
-					;;
+				DONE) echo -ne "${DONE} DONE ${NORMAL}";;
+				WARN) echo -ne "${WARN} WARN ${NORMAL}";;
+				FAIL) echo -ne "${FAIL} FAIL ${NORMAL}";;
+				SKIP) echo -ne "${SKIP} SKIP ${NORMAL}";;
+				ON|ENAB*) echo -ne "${DONE} ENAB ${NORMAL}";;
+				OFF|DISA*) echo -ne "${FAIL} DISA ${NORMAL}";;
 			esac
+			echo -ne "${BRACKET_R}\n"
 			;;
 		build_stage)
 			MESSAGE=$2
@@ -286,14 +309,14 @@ beautify()
 
 				echo -ne "${PROGRAM}"
 				if ! [ "$OPTIONS" == "" ]; then
-					echo -ne "${SET_OPT_COL}[ ${BOLD}${OPTIONS}${NORMAL} ]"
+					echo -ne "${SET_OPT_COL}${BRACKET_L} ${BOLD}${OPTIONS}${NORMAL} ${BRACKET_R}"
 				fi
 
 				if [ "${PKG_VER}" == "${SNAME}" ] || [ "${PKG_VER}" == "LFS" ]; then
 					echo -ne "${SET_RESULT_COL}"
 				else
-					echo -ne "${SET_VER_COL}[ ${BOLD}${SET_VER_COL_REAL}${PKG_VER}"
-					echo -ne "${NORMAL} ]${SET_RESULT_COL}"
+					echo -ne "${SET_VER_COL}${BRACKET_L} ${BOLD}${SET_VER_COL_REAL}${PKG_VER}"
+					echo -ne "${NORMAL} ${BRACKET_R}${SET_RESULT_COL}"
 				fi
 			done
 			;;
@@ -307,19 +330,11 @@ beautify()
 			fi
 
 			SET_TIME_COL_REAL=`position_cursor $RESULT_COL $PKG_TIME -3`
+			echo -ne "${SET_TIME_COL}${BRACKET_L} ${BOLD}${SET_TIME_COL_REAL}$PKG_TIME${NORMAL} ${BRACKET_R}"
 			case "$RESULT" in
-				DONE)
-					echo -ne "${SET_TIME_COL}[ ${BOLD}${SET_TIME_COL_REAL}$PKG_TIME${NORMAL} ]"
-					echo -ne "${SET_RESULT_COL}[${DONE} DONE ${NORMAL}]\n"
-					;;
-				FAIL)
-					echo -ne "${SET_TIME_COL}[ ${BOLD}${SET_TIME_COL_REAL}$PKG_TIME${NORMAL} ]"
-					echo -ne "${SET_RESULT_COL}[${FAIL} FAIL ${NORMAL}]\n"
-					;;
-				SKIP)
-					echo -ne "${SET_TIME_COL}[ ${BOLD}${SET_TIME_COL_REAL}$PKG_TIME${NORMAL} ]"
-					echo -ne "${SET_RESULT_COL}[${SKIP} SKIP ${NORMAL}]\n"
-					;;
+				DONE) echo -ne "${SET_RESULT_COL}${BRACKET_L}${DONE} DONE ${NORMAL}${BRACKET_R}\n";;
+				FAIL) echo -ne "${SET_RESULT_COL}${BRACKET_L}${FAIL} FAIL ${NORMAL}${BRACKET_R}\n";;
+				SKIP) echo -ne "${SET_RESULT_COL}${BRACKET_L}${SKIP} SKIP ${NORMAL}${BRACKET_R}\n";;
 			esac
 			;;
 	esac
@@ -357,13 +372,14 @@ stdumount() {
 
 exiterror() {
 	stdumount
-	
+
 	beautify message FAIL
- 
+
 	echo -ne "${FAIL}ERROR${NORMAL}: ${BOLD}$*${NORMAL}\n"
 	[ -z "$LOGFILE" ] || \
 	echo "       Check $LOGFILE for errors if applicable"
 	build_spy error
+	rm -f $RUNNING
 	exit 1
 } # End of exiterror()
 
@@ -470,7 +486,6 @@ toolchain_make() {
 		CONFIG_ROOT=$CONFIG_ROOT \
 		LINKER=$LINKER \
 		TOOLS_DIR=$TOOLS_DIR \
-		CTOOLS_DIR=$CTOOLS_DIR \
 		MACHINE="$MACHINE" \
 		MACHINE_REAL="$MACHINE_REAL" \
 		IFS_HOST="$IFS_HOST" \
@@ -585,7 +600,6 @@ ipfire_make() {
 # This prepares the build environment                                          #
 ################################################################################
 prepareenv() {
-
 	LOGFILE=$BASEDIR/log_${MACHINE}/_build.00-preparation.log
 	export LOGFILE
 	mkdir -p $BASEDIR/log_${MACHINE}/01_toolchain 2>/dev/null
@@ -772,6 +786,7 @@ build() {
 	#only restore on a clean disk
 
 	local BLD_TIME_START=`date +%s`
+	touch $RUNNING
 
 	echo -ne "Building for ${BOLD}${TARGET} (${MACHINE}) on ${MACHINE_REAL}${NORMAL}\n"
 
@@ -820,27 +835,71 @@ build() {
 	local BLD_TIME_END=`date +%s`
 	build_spy set duration $[ $BLD_TIME_END - $BLD_TIME_START ]
 	build_spy idle
+	rm -f $RUNNING
 }
 
 gettoolchain() {
+	check_user
 	if [ ! -f $BASEDIR/cache/toolchains/$TOOLCHAINNAME.tar.bz2 ]; then
 		URL_TOOLCHAIN=$(grep URL_TOOLCHAIN lfs/Config | awk '{ print $3 }')
 		DIR_TOOLCHAIN="$BASEDIR/cache/toolchains"
 
 		echo "Loading toolchain for $MACHINE"
-		BASEDIR=$BASEDIR DIR_TMP=/tmp DIR_DL=$DIR_TOOLCHAIN \
-			sh $BASEDIR/tools/downloader $URL_TOOLCHAIN $TOOLCHAINNAME.tar.bz2
-
-		if [ $? -eq 0 ]; then
-			echo -n "Toolchain was successfully downloaded"
-			beautify message DONE
-		else
-			echo -n "ERROR: Downloading toolchain \"$TOOLCHAINNAME\""
-			beautify message FAIL
-			echo "Precompiled toolchain not always available for every machine"
-		fi
+		scp -2C ${IPFIRE_USER}@${URL_TOOLCHAIN}/$TOOLCHAINNAME.tar.bz2 \
+			${DIR_TOOLCHAIN}
 	else
 		echo -n "Toolchain \"$TOOLCHAINNAME\" is already existing"
 		beautify message SKIP
 	fi
+}
+
+puttoolchain() {
+	check_user
+	if [ -f $BASEDIR/cache/toolchains/$TOOLCHAINNAME.tar.bz2 ]; then
+		URL_TOOLCHAIN=$(grep URL_TOOLCHAIN lfs/Config | awk '{ print $3 }')
+		DIR_TOOLCHAIN="$BASEDIR/cache/toolchains"
+
+		echo "Pushing toolchain for $MACHINE"
+		scp -2C ${DIR_TOOLCHAIN}/$TOOLCHAINNAME.tar.bz2 \
+			${IPFIRE_USER}@${URL_TOOLCHAIN}
+	else
+		echo -n "Toolchain \"$TOOLCHAINNAME\" is not existing. "
+		echo -n "Run \"./make.sh build\", first"
+		beautify message SKIP
+	fi
+}
+
+getsource() {
+	if [ ! -d $BASEDIR/cache ]; then
+		mkdir -p $BASEDIR/cache/{tarballs,patches}
+	fi
+	mkdir -p $BASEDIR/log_${MACHINE}
+	echo -e "${BOLD}Preload all source files${NORMAL}"
+	cd $BASEDIR/lfs
+	for i in *; do
+		if [ -f "$i" -a "$i" != "Config" ]; then
+			make -s -f $i \
+			LFS_BASEDIR=$BASEDIR \
+			MESSAGE="$i\t" \
+			SSP=$SSP \
+			PIE=$PIE \
+			PAX=$PAX download 2>> $LOGFILE
+			[ $? -ne 0 ] && beautify message FAIL
+		fi
+	done
+	cd $BASEDIR
+}
+
+putsource() {
+	check_user
+	URL_SOURCE=$(grep URL_SOURCE lfs/Config | awk '{ print $3 }')
+	REMOTE_FILES=$(echo "ls -1" | sftp -C ${IPFIRE_USER}@${URL_SOURCE})
+
+	cd $BASEDIR/cache/tarballs/
+	for file in $(ls -1); do
+		grep -q "$file" <<<$REMOTE_FILES && continue
+		NEW_FILES="$NEW_FILES $file"
+	done
+	[ -n "$NEW_FILES" ] && scp -2C $NEW_FILES ${IPFIRE_USER}@${URL_SOURCE}
+	cd $BASEDIR
 }
