Cheking in a first version of building the cdrom for a specific cpu. This will bring some more performance on the vias and make the distribution more compatible with older kinds of pc.
git-svn-id: http://svn.ipfire.org/svn/ipfire/trunk@1188 ea5c0bd1-69bd-2848-81d8-4f18e57aeed8

diff --git a/tools/make-include b/tools/make-include
--- a/tools/make-include
+++ b/tools/make-include
@@ -26,8 +26,9 @@
 
 CONFIG_ROOT=/etc/ipfire					# Configuration rootdir
 NICE=10													# Nice level
+TARGET=i686											# Default target
 KVER=`grep --max-count=1 VER lfs/linux | awk '{ print $3 }' | tr -d '\n'; grep --max-count=1 FULLVER lfs/linux | awk '{ print $3 }' | cut -c 7-| tail -1`
-MACHINE=`uname -m`
+MACHINE_REAL=`uname -m`
 SVN_REVISION=`svn info | grep Revision | cut -c 11-`
 
 PARALLELISM=$(( $(grep processor < /proc/cpuinfo | wc -l) * 2 + 1 ))	# Parallelism flag
@@ -68,22 +69,44 @@ fi
 #
 ###############################################################################
 
-if [ 'i686' = $MACHINE -o 'i586' = $MACHINE -o 'i486' = $MACHINE -o 'i386' = $MACHINE ]; then
-	MACHINE=i586
-	MACHINE_REAL=i686
-	LINKER=/lib/ld-linux.so.2
-	C2FLAGS="-O2 -fomit-frame-pointer -march=i586 -pipe"
-	CXX2FLAGS="-O2 -fomit-frame-pointer -march=i586 -pipe"
-elif [ 'x86_64' = $MACHINE ]; then
-	MACHINE=i586
-	MACHINE_REAL=x86_64
-	LINKER=/lib/ld-linux.so.2
-	C2FLAGS="-O2 -fomit-frame-pointer -march=i586 -pipe"
-	CXX2FLAGS="-O2 -fomit-frame-pointer -march=i586 -pipe"
+if [ 'i686' = $MACHINE_REAL \
+	-o 'i586' = $MACHINE_REAL \
+	-o 'i486' = $MACHINE_REAL \
+	-o 'i386' = $MACHINE_REAL \
+	-o 'x86_64' = $MACHINE_REAL ]; then
+	:
 else
 	beautify message FAIL
-	echo "Can't determine your architecture - $MACHINE"
-  exit 1
+	echo "Can't determine your architecture - $MACHINE_REAL"
+	exit 1
+fi
+
+if [ 'i686' = $TARGET -o 'i586' = $TARGET \
+	-o 'i486' = $TARGET -o 'i386' = $TARGET ]; then
+	MACHINE=${TARGET}
+	MACHINE_REAL=${MACHINE_REAL}
+	LINKER=/lib/ld-linux.so.2
+	C2HOST="${MACHINE}-pc-linux-gnu"
+	C2FLAGS="-march=${MACHINE} -O2 -pipe -fomit-frame-pointer"
+	CXX2FLAGS="${C2FLAGS}"
+elif [ 'via-c7' = $TARGET ]; then
+	MACHINE=i686
+	MACHINE_REAL=${MACHINE_REAL}
+	LINKER=/lib/ld-linux.so.2
+	C2HOST="i686-pc-linux-gnu"
+	C2FLAGS="-march=${MACHINE} -mmmx -msse -msse2 -msse3 -O2 -pipe -fomit-frame-pointer"
+	CXX2FLAGS="${C2FLAGS}"
+elif [ 'via-c3' = $TARGET ]; then
+	MACHINE=i586
+	MACHINE_REAL=${MACHINE_REAL}
+	LINKER=/lib/ld-linux.so.2
+	C2HOST="i586-pc-linux-gnu"
+	C2FLAGS="-march=c3 -m3dnow -O2 -pipe -fomit-frame-pointer"
+	CXX2FLAGS="${C2FLAGS}"
+else
+	beautify message FAIL
+	echo "Not a valid target arch (i686|i586|i486|i386|via-c7|via-c3) - $TARGET"
+	exit 1
 fi
 
 mkdir $BASEDIR/log_${MACHINE}/ 2>/dev/null
@@ -327,7 +350,7 @@ entershell() {
 	chroot $LFS $TOOLS_DIR/bin/env -i \
 		HOME=/root \
 		TERM=$TERM \
-		PS1="${BOLD}[chroot-${MACHINE}]${NORMAL} \u:\w\$ " \
+		PS1="${BOLD}[chroot-${MACHINE}-${TARGET}]${NORMAL} \u:\w\$ " \
 		PATH=$PATH \
 		CONFIG_ROOT=${CONFIG_ROOT} \
 		VERSION=${VERSION} \
@@ -344,6 +367,7 @@ entershell() {
 		INSTALLER_DIR=$INSTALLER_DIR \
 		MACHINE="$MACHINE" \
 		MACHINE_REAL="$MACHINE_REAL" \
+		CHOST="$C2HOST" \
 		CFLAGS="$C2FLAGS" \
 		CXXFLAGS="$CXX2FLAGS" \
 		KVER=$KVER \
@@ -476,6 +500,7 @@ ipfire_make() {
 		IMAGES_DIR=$IMAGES_DIR \
 		MACHINE="$MACHINE" \
 		MACHINE_REAL="$MACHINE_REAL" \
+		CHOST="$C2HOST" \
 		CFLAGS="$C2FLAGS" \
 		CXXFLAGS="$CXX2FLAGS" \
 		KVER=$KVER \
