naoki: Code cleanup. No functional changes.

diff --git a/tools/naoki-include b/tools/naoki-include
--- a/tools/naoki-include
+++ b/tools/naoki-include
@@ -1,11 +1,15 @@
 #!/bin/bash
 
-BASEDIR="/ipfire-3.x/"
+if [ -z "${BASEDIR}" ]; then
+	echo "${0##*/}: ERROR: BASEDIR is not set." >&2
+	exit 1
+fi
 
-LOGFILE=${BASEDIR}/naoki.log
+export NAOKI_INCLUDE=1
 
-. ${BASEDIR}/tools/naoki-functions
+. ${BASEDIR}/tools/common-include
+
 . ${BASEDIR}/tools/naoki-constants
-
+. ${BASEDIR}/tools/naoki-functions
 
 log DEBUG "Started up naoki instance with pid $$"
