bonding; Validate any MAC address passed
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

diff --git a/src/hooks/ports/bonding b/src/hooks/ports/bonding
--- a/src/hooks/ports/bonding
+++ b/src/hooks/ports/bonding
@@ -39,8 +39,14 @@ hook_parse_cmdline() {
 	while [ $# -gt 0 ]; do
 		case "${1}" in
 			--address=*)
-				ADDRESS=$(cli_get_val "${1}")
+				ADDRESS="$(cli_get_val "${1}")"
+
+				if ! mac_is_valid "${ADDRESS}"; then
+					error "Invalid MAC address: ${ADDRESS}"
+					return ${EXIT_ERROR}
+				fi
 				;;
+
 			--miimon=*)
 				MIIMON=$(cli_get_val "${1}")
 				;;
