bridge: Simplify the hook and make it more robust against missing ports

diff --git a/src/hooks/ports/ethernet b/src/hooks/ports/ethernet
--- a/src/hooks/ports/ethernet
+++ b/src/hooks/ports/ethernet
@@ -51,6 +51,11 @@ function hook_up() {
 	local port=${1}
 	assert isset port
 
+	if ! device_exists "${port}"; then
+		log WARNING "Cannot bring up port '${port}' which does not exist"
+		exit ${EXIT_OK}
+	fi
+
 	# Read in the confguration file.
 	port_settings_read "${port}" ${HOOK_SETTINGS}
 
@@ -60,7 +65,7 @@ function hook_up() {
 	fi
 
 	# Bring up the device.
-	device_set_up ${port}
+	device_set_up "${port}"
 
 	exit ${EXIT_OK}
 }
diff --git a/src/hooks/zones/bridge b/src/hooks/zones/bridge
--- a/src/hooks/zones/bridge
+++ b/src/hooks/zones/bridge
@@ -283,15 +283,23 @@ function hook_port_up() {
 	local zone="${1}"
 	local port="${2}"
 
-	zone_port_settings_read "${zone}" "${port}" ${HOOK_PORT_SETTINGS}
-
+	# Try bringing up the port
 	port_up "${port}"
 
-	# Set same MTU to device that the bridge has got
-	device_set_mtu "${port}" $(device_get_mtu "${zone}")
+	# If the port could not be brought up, we will
+	# log an error message and exit.
+	if ! device_exists "${port}"; then
+		log WARNING "Port '${port}' cannot be attached to zone '${zone}' as it does not exist"
+		exit ${EXIT_OK}
+	fi
 
+	# Read configuration values
+	zone_port_settings_read "${zone}" "${port}" ${HOOK_PORT_SETTINGS}
+
+	# Attach the port to the bridge
 	bridge_attach_device "${zone}" "${port}"
 
+	# Set STP configuration
 	if isset COST; then
 		stp_port_set_cost "${zone}" "${port}" "${COST}"
 	fi
