vlan: Refactor vlan_create()
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

diff --git a/src/hooks/ports/vlan b/src/hooks/ports/vlan
--- a/src/hooks/ports/vlan
+++ b/src/hooks/ports/vlan
@@ -114,9 +114,15 @@ hook_create() {
 	fi
 
 	# Create the VLAN device
-	vlan_create "${port}" "${PARENT_PORT}" "${TAG}" "${ADDRESS}"
+	if ! vlan_create "${port}" \
+			--address="${ADDRESS}" \
+			--parent="${PARENT_PORT}" \
+			--tag="${TAG}"; then
+		error "Could not create port: ${port}"
+		return ${EXIT_ERROR}
+	fi
 
-	exit ${EXIT_OK}
+	return ${EXIT_OK}
 }
 
 hook_remove() {
