vlan: Create partent port (if necessary)
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

diff --git a/src/hooks/ports/vlan b/src/hooks/ports/vlan
--- a/src/hooks/ports/vlan
+++ b/src/hooks/ports/vlan
@@ -113,6 +113,12 @@ hook_create() {
 		return ${EXIT_ERROR}
 	fi
 
+	# Create the partent port first
+	if ! port_create "${PARENT_PORT}"; then
+		error "Could not bring up parent port: ${PARENT_PORT}"
+		return ${EXIT_ERROR}
+	fi
+
 	# Create the VLAN device
 	if ! vlan_create "${port}" \
 			--address="${ADDRESS}" \
