wireless: Validate channels
Signed-off-by: Michael Tremer <michael.tremer@ipfire.org>

diff --git a/src/hooks/ports/wireless-mesh b/src/hooks/ports/wireless-mesh
--- a/src/hooks/ports/wireless-mesh
+++ b/src/hooks/ports/wireless-mesh
@@ -70,6 +70,11 @@ hook_parse_cmdline() {
 	fi
 
 	# XXX check if wireless channel is valid
+	# Check if channel is valid
+	if ! wireless_channel_is_valid "${CHANNEL}"; then
+		log ERROR "Channel is invalid: ${CHANNEL}"
+		return ${EXIT_ERROR}
+	fi
 }
 
 hook_create() {
