Split port hooks in to (create|remove|up|down) actions
The port hooks formerly had two functions that brought the device
up or down. That caused some problems with hotplugging of the zones.

Now the entire process has been split into four functions that
every port hooks has to implement.

create:
	Creates the device but does not bring it up yet. This will
	usually trigger a hotplug event so that various other port
	or zone hooks can attach the device or do similar actions.

up:
	Essentially brings up the device, just like:
	  ip link set devX up

	The action should propagate to any slave devices.

down:
	Does essentially the opposite of "up" and should propagate
	to the slaves as well.

remove:
	Removes any virtual devices and cleans up. This will also
	trigger a hotplug event so that all connected hooks will
	be notified about the removal.

diff --git a/src/header-port b/src/header-port
--- a/src/header-port
+++ b/src/header-port
@@ -72,3 +72,57 @@ function hook_status() {
 	cli_device_headline "${port}" --long
 	exit ${EXIT_OK}
 }
+
+# Create any virtual devices, but don't bring them up
+# Must tolerate that the device may already exist
+function hook_create() {
+	cmd_not_implemented
+}
+
+# Must tolerate that the device may not exist
+function hook_remove() {
+	cmd_not_implemented
+}
+
+# Just bring up the device
+function hook_default_up() {
+	local port="${1}"
+	assert isset port
+
+	if ! device_exists "${port}"; then
+		log ERROR "Port '${port}' does not exist and cannot be brought up"
+		exit ${EXIT_ERROR}
+	fi
+
+	# Bring up the port
+	device_set_up "${port}"
+
+	# Bring up all slaves if the port has any
+	local slave
+	for slave in $(port_get_slaves "${port}"); do
+		port_up "${slave}"
+	done
+}
+
+function hook_up() {
+	hook_default_up $@
+}
+
+function hook_default_down() {
+	local port="${1}"
+	assert isset port
+
+	if device_exists "${port}"; then
+		device_set_down "${port}"
+	fi
+
+	# Bring down all slaves if the port has any
+	local slave
+	for slave in $(port_get_slaves "${port}"); do
+		port_down "${slave}"
+	done
+}
+
+function hook_down() {
+	hook_default_down $@
+}
diff --git a/src/hooks/ports/bonding b/src/hooks/ports/bonding
--- a/src/hooks/ports/bonding
+++ b/src/hooks/ports/bonding
@@ -36,7 +36,7 @@ function hook_check() {
 	assert isinteger MIIMON
 }
 
-function hook_create() {
+function hook_new() {
 	hook_edit $@
 }
 
@@ -96,47 +96,122 @@ function hook_edit() {
 	exit ${EXIT_OK}
 }
 
-function hook_up() {
-	local device="${1}"
-	assert isset device
+function hook_create() {
+	local port="${1}"
+	assert isset port
 
-	port_settings_read "${device}" ${HOOK_SETTINGS}
+	# Exit silently if the device already exists
+	device_exists "${port}" && exit ${EXIT_OK}
 
-	if ! device_exists ${device}; then
-		bonding_create "${device}" \
-			--address="${ADDRESS}" \
-			--mode="${MODE}" || exit ${EXIT_ERROR}
-	fi
+	port_settings_read "${port}" ${HOOK_SETTINGS}
 
-	device_set_address "${device}" "${ADDRESS}"
-	bonding_set_miimon "${device}" "${MIIMON}"
-	device_set_up "${device}"
+	# Create the bonding devices
+	bonding_create "${port}" \
+		--address="${ADDRESS}" \
+		--mode="${MODE}" || exit ${EXIT_ERROR}
 
-	local slave
-	for slave in $(unquote ${SLAVES}); do
-		if ! device_exists ${slave}; then
-			log WARNING "Cannot enslave '${slave}' to '${device}' as it is not available"
-			continue
-		fi
-
-		bonding_enslave_device "${device}" "${slave}"
-	done
-
-	# Bring up the device.
-	device_set_up "${device}"
+	bonding_set_miimon "${port}" "${MIIMON}"
 
 	exit ${EXIT_OK}
 }
 
-function hook_down() {
-	local device="${1}"
+function hook_remove() {
+	local port="${1}"
+	assert isset port
 
-	bonding_remove "${device}"
+	port_settings_read "${port}" ${HOOK_SETTINGS}
 
+	# Remove the bonding device
+	if device_exists "${port}"; then
+		bonding_remove "${port}"
+	fi
+}
+
+function hook_up() {
+	local port="${1}"
+	assert isset port
+
+	port_settings_read "${port}" ${HOOK_SETTINGS}
+
+	# Execute the default action
+	hook_default_up "${port}"
+
+	# Bring up all slaves
 	local slave
-	for slave in ${SLAVES}; do
-		device_set_down "${slave}"
+	for slave in $(unquote ${SLAVES}); do
+		port_up "${slave}"
+	done
+}
+
+function hook_down() {
+	local port="${1}"
+	assert isset port
+
+	port_settings_read "${port}" ${HOOK_SETTINGS}
+
+	# Bring down all slaves
+	local slave
+	for slave in $(unquote ${SLAVES}); do
+		port_down "${slave}"
 	done
 
-	exit ${EXIT_OK}
+	# Execute the default action
+	hook_default_down "${port}"
+}
+
+function hook_hotplug() {
+	local port="${1}"
+	assert isset port
+
+	case "$(hotplug_action)" in
+		add)
+			# Handle events of the same interface
+			if hotplug_event_port_is_interface "${port}"; then
+				# Read configuration
+				port_settings_read "${port}" ${HOOK_SETTINGS}
+
+				# Bring up all slaves
+				# Attach those which already exist and try to create
+				# those which don't exist yet. They will be attached
+				# in their own hotplug event.
+				local slave
+				for slave in $(unquote ${SLAVES}); do
+					if device_exists "${slave}"; then
+						bonding_enslave_device "${port}" "${slave}"
+					else
+						port_create "${slave}"
+					fi
+				done
+
+				exit ${EXIT_OK}
+
+			# Handle slave devices that have just been created and
+			# attach them.
+			elif hotplug_event_interface_is_slave_of_port "${port}"; then
+				bonding_enslave_device "${port}" "${INTERFACE}"
+
+				# If the parent device has been set up, we will
+				# bring up the slave device as well.
+				if device_is_up "${port}"; then
+					port_up "${INTERFACE}"
+				fi
+			fi
+
+			exit ${EXIT_OK}
+			;;
+
+		remove)
+			if hotplug_event_port_is_interface "${port}"; then
+				# Bring down all slaves after the parent device went away
+				local slave
+				for slave in $(port_get_slaves "${port}"); do
+					port_remove "${slave}"
+				done
+
+				exit ${EXIT_OK}
+			fi
+			;;
+	esac
+
+	exit ${EXIT_NOT_HANDLED}
 }
diff --git a/src/hooks/ports/wireless-ap b/src/hooks/ports/wireless-ap
--- a/src/hooks/ports/wireless-ap
+++ b/src/hooks/ports/wireless-ap
@@ -53,7 +53,7 @@ function hook_check() {
 	fi
 }
 
-function hook_create() {
+function hook_new() {
 	while [ $# -gt 0 ]; do
 		case "${1}" in
 			--broadcast-ssid=*)
@@ -139,9 +139,11 @@ function hook_edit() {
 	exit ${EXIT_OK}	
 }
 
-function hook_up() {
-	local port=${1}
+function hook_create() {
+	local port="${1}"
 	assert isset port
+
+	device_exists "${port}" && exit ${EXIT_OK}
 
 	port_settings_read "${port}" ${HOOK_SETTINGS}
 
@@ -152,26 +154,17 @@ function hook_up() {
 		exit ${EXIT_ERROR}
 	fi
 
-	# Create the wireless device, if it does not exist, yet.
-	if ! device_exists ${port}; then
-		wireless_create ${port} --phy="${phy}" --type="ap" \
-			--address="${ADDRESS}"
-	fi
-
-	# Start the hostapd service.
-	#hostapd_start ${port}
-	local ret=$?
-
-	if [ ${ret} -ne ${EXIT_OK} ]; then
-		log ERROR "Could not start hostapd on port '${port}': ${ret}"
-		exit ${EXIT_ERROR}
-	fi
+	# Create the wireless device
+	wireless_create "${port}" \
+		--phy="${phy}" \
+		--type="ap" \
+		--address="${ADDRESS}"
 
 	exit ${EXIT_OK}
 }
 
-function hook_down() {
-	local port=${1}
+function hook_remove() {
+	local port="${1}"
 	assert isset port
 
 	# Remove the device if present
@@ -182,19 +175,34 @@ function hook_down() {
 	exit ${EXIT_OK}
 }
 
+function hook_up() {
+	local port="${1}"
+	assert isset port
+
+	# The port must already exist before
+	# hostapd is started. Otherwise it will
+	# fail horribly over and over again.
+	assert device_exists "${port}"
+
+	hostapd_start "${port}"
+}
+
+function hook_down() {
+	local port="${1}"
+	assert isset port
+
+	hostapd_stop "${port}"
+}
+
 function hook_hotplug() {
 	local port="${1}"
 	assert isset port
 
 	case "$(hotplug_action)" in
 		add)
-			# Start hostapd after the port has been brought up
-			if hotplug_event_port_is_interface "${port}"; then
-				hostapd_start "${port}"
-
-			# Bring up the port when the phy is plugged in
-			elif hotplug_event_port_uses_phy "${port}"; then
-				hook_up "${port}"
+			# Create the port when the phy is plugged in
+			if hotplug_event_port_uses_phy "${port}"; then
+				hook_create "${port}"
 			fi
 			;;
 
@@ -202,13 +210,11 @@ function hook_hotplug() {
 			# Stop hostapd
 			if hotplug_event_port_is_interface "${port}"; then
 				hostapd_stop "${port}"
-			fi
-			;;
 
-		*)
-			exit ${EXIT_NOT_HANDLED}
+				exit ${EXIT_OK}
+			fi
 			;;
 	esac
 
-	exit ${EXIT_OK}
+	exit ${EXIT_NOT_HANDLED}
 }
