network: Some general changes.
New hook for interface trunks (experimental).

Major rewritements of the port hooks.

diff --git a/src/network/hooks/bonding b/src/network/hooks/bonding
--- a/src/network/hooks/bonding
+++ b/src/network/hooks/bonding
@@ -2,35 +2,153 @@
 ########################################################################
 # Begin $NETWORK_DEVICES/services/bonding
 #
-# Description : Interface Bonding Script
+# Description : Bonding Script
 #
 # Authors     : Michael Tremer - michael.tremer@ipfire.org
 #
 # Version     : 00.00
 #
-# Notes       : This script collects two or more interfaces in one
-#               bonding intreface.
+# Notes       : This script adds bonding support.
 #
 ########################################################################
 
-. /etc/init/functions
-. ${CONFIG}
+. /lib/network/hook-header
 
-case "${2}" in
-	up)
-		MESSAGE="Bringing up bonding interface ${1}..."
-		ifenslave ${1} ${SLAVE_INTERFACES}
-		evaluate_retval
-	;;
+HOOK_NAME=bonding
+HOOK_TYPE=port
 
-	down)
-		MESSAGE="Bringing down bonding interface ${1}..."
-		modprobe -r bonding 2>/dev/null
-		evaluate_retval
-	;;
+DEFAULT_MODE=
+
+# TODO: Need to detect link failures!
+
+function port_name() {
+	echo "${zone}t+"
+}
+
+case "${action}" in
+	help)
+		;;
+
+	info)
+		echo "HOOK_NAME=${HOOK_NAME}"
+		echo "HOOK_TYPE=${HOOK_TYPE}"
+		;;
+
+	pre-up)
+		if ! grep -q ^bonding /proc/modules; then
+			modprobe bonding
+			echo "-bond0" > /sys/class/net/bonding_masters
+		fi
+
+		if device_exists ${MAC}; then
+			device=$(devicify ${MAC})
+			if ! device_is_bonding ${device}; then
+				log_failure_msg "Device \"${device}\" is up, but not a bonding device."
+				exit ${EXIT_ERR}
+			fi
+			exit ${EXIT_OK}
+		fi
+
+		device=$(device_get_free $(port_name))
+		echo "+${device}" > /sys/class/net/bonding_masters
+		ip link set ${device} address ${MAC}
+	
+		[ -n "${MODE}" ] && \
+			echo "${MODE}" > /sys/class/net/${device}/bonding/mode
+	
+		for slave in ${SLAVES}; do
+			if device_exists ${slave}; then
+				if device_is_up ${slave}; then
+					log_warning_msg "Cannot enslave device \"${slave}\"."
+					continue
+				fi
+				echo "+$(devicify ${slave})" > /sys/class/net/${device}/bonding/slaves
+				device_rename "$(devicify ${slave})" "${device}s+"
+			else
+				log_warning_msg "Device ${slave} does not exist."
+			fi
+		done
+	
+		ip link set ${device} up
+	
+		log_success_msg "Setting up trunk ${MAC}..."
+		;;
+
+	post-up)
+		device=$(devicify ${MAC})
+		if ! zone_has_device_attached ${zone} ${device}; then
+			zone_add_port ${zone} ${device}
+		fi
+		;;
+
+	pre-down)
+		device=$(devicify ${MAC})
+		if zone_has_device_attached ${zone} ${device}; then
+			zone_del_port ${zone} ${device}
+		fi
+		;;
+
+	post-down)
+		device=$(devicify ${MAC})
+		if port_is_up ${device}; then
+			MESSAGE="Pulling down trunk ${MAC}..."
+			ip link set ${device} down
+			evaluate_retval
+			echo "-${device}" > /sys/class/net/bonding_masters
+		fi
+		;;
+
+	add)
+		MAC=$(mac_generate)
+		MODE=${DEFAULT_MODE}
+
+		while [ $# -gt 0 ]; do
+			case "${1}" in
+				--mac=*)
+					MAC=${1#--mac=}
+					;;
+				--mode=*)
+					MODE=${1#--mode=}
+					;;
+				*)
+					SLAVES="${SLAVES} $(macify ${1})"
+					;;
+			esac
+			shift
+		done
+
+		UUID=$(uuid)
+		cat <<EOF > ${CONFIG_UUIDS}/${UUID}
+HOOK="${HOOK_NAME}"
+MAC="${MAC}"
+MODE="${MODE}"
+SLAVES="$(echo ${SLAVES})"
+EOF
+		ln -sf ${CONFIG_UUIDS}/${UUID} \
+			${CONFIG_ZONES}/${zone}/${HOOK_NAME}-${UUID}
+
+		log_success_msg "Configuration successfully saved!"
+		echo    "      MAC address : ${MAC}"
+		echo    "      Mode        : ${MODE}"
+		echo    "      Slaves      : $(echo ${SLAVES})"
+		;;
+
+	rem)
+		;;
+
+	status)
+		device_is_up $(devicify ${MAC})
+		RET=$?
+		if [ $RET -eq 0 ]; then
+			log_success_msg "Port $(port_name) is up"
+		else
+			log_failure_msg "Port $(port_name) is down"
+		fi
+		exit ${RET}
+		;;
 
 	*)
-		echo "Usage: ${0} [interface] {up|down}"
+		echo "Usage: ${0} [interface] {up|down|add|remove|attach|detach|status}"
 		exit 1
 	;;
 esac
